apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:4wDoarEZ16tV5FZaiYLd806XRz0y2aAnmDOytCaqUhL63hpxDHOFMAqsFQwu5SHBVZ9ozyNRaubUi9idRThRH5tumB4CA4QGx6ehiJrYqPopRMbz70qGtQPs8GMGUA==,iv:2y0Sds5CF2i0cLUfSrCGPTZLE6sxxpxNVCKFOtn3EUA=,tag:wLEoDFdtE5rlrOMtVpwIOA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cfx8fyl766yy5q9tx6ce0hh3du7aepw38z6pdl0tttfj6txtsy4qv3cj0d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOSXlHOWVFc2R4K3lpL0Q5
            VEduRWtrQ1VMd0RsdXdyTGswRHliL1BGWWhFCnJOcENxdG1EVm9Lb2dhQ09VQWho
            UG5OVHFFY3ErcXRQMzVVcTR6WGg4N1kKLS0tIFNLMTREbWN0RjRQNmdPazUwaFNr
            WnRIOEhiMS9WVGZWaHlqWktLTGtrd1EK0LjL06r3CwaNO/ElCxas6Z0Ktru2OJ11
            dHKJ+JsH8qmbYOk7WcOB8xXlVmgMpptwuibLNh0EDFT0PAwsjMNj9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-23T03:14:47Z"
    mac: ENC[AES256_GCM,data:JTvJcsoZmgrMTG6ksvsuAV+1WUIdQ48bmp5huOzLS6vVFqZTb/wBSdln4m8KAeAdvepW8zS6Nkq4DTOi80Pc/11EaKs7ckXiW/pEP7g6k0rmpe6Q+WPab8SOq6fQrd5nAaNGE8+AJpRYzSt31GIusQVm1ViN2pwcuOkyj6Z0RSU=,iv:5NCEkPo/BQi7nxnDxobzZaEbZIhlDHZDVn5sTT+FJ3Q=,tag:K1iZPUgG/8t8e8+KbcvqCw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
